services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


  # web:
  #   build: .
  #   container_name: fastapi_app
  #   restart: always
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"